spring:
  #thymeleaf模块配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8 
    #清除缓存，实现热部署。也就是修改了html后不用重启，刷新页面就能看到效果。再回到浏览器刷新，就能看到效果了     
    cache: false  
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name:  com.mysql.cj.jdbc.Driver
  #单个redis配置  
  redis:
    #Redis服务器地址
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password:
    # Redis数据库索引（默认为0）
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 32
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 0


#设置项目路径和端口号  
server:
  port: 8080
  servlet: 
    context-path: /spring-main
    
#pagehelper分页插件配置
pagehelper: 
  helperDialect: mysql
  
#静态js/css资源文件
resource:
  #协议
  protocol: http
  #ip地址
  ip: 127.0.0.1
  #端口号
  port: 8001
  #项目名称
  project_name: spring-resource



#baseUrl: http://127.0.0.1:8001/spring-resource/ace-master/assets/css/bootstrap.min.css
  